name: TranspireMining
version: ${project.version}
main: rpgplugin.rpgplugin.RPGPluginrpgplugin.rpgplugin.RPGPlugin
softdepend: [HolographicDisplays]
api-version: 1.16
commands:
  flares:
    aliases: [tflare, flare, tflares]
